### ISSUE TITLE
Map Soft-RoCE memory region to same of IVSHMEM or lgProxy

### ISSUE THREAD

**Issue by beanpaisly** [telescope-proj/libtrf#7]
In cases where clients are laptops that do not come with RDMA NICs it makes sense to use Soft-RoCE.

To avoid extra memory copies, is it possible to map Soft-RoCE memory region to the same of IVSHMEM or lgProxy?
Or is this use case already covered by lgProxy ?

**Comment by beanfacts** [comment]
LibTRF will attempt to register whatever memory region you specify via the API. It is up to the user to verify the memory region can be paged into physical memory (i.e., you would be able to `mlock()` it). The implementation simply calls Libfabric memory registration internally. 

https://github.com/telescope-proj/libtrf/blob/main/libtrf/include/internal/trfi_fabric.h#L36

As such the `rdma_rxe` or `siw` software RDMA modules should be able to register any valid memory region (e.g. IVSHMEM). However as with all software networking, you will still end up with at least one memory copy from the receive side SKB; after all, the payload still needs to be extracted from the packet. This just happens in kernel space and applications are not aware of it.

In LGProxy, the entire IVSHMEM region, whether that region is backed by /dev/kvmfr* or /dev/shm/*, is registered for zero copy data placement through the LibTRF API. The offset from the start of the IVSHMEM region to the start of the framebuffer is tracked and swapped on every frame update.

https://github.com/telescope-proj/lgproxy/blob/main/lgproxy/source/lp_source.c#L310
https://github.com/telescope-proj/lgproxy/blob/main/lgproxy/source/lp_source.c#L401
